### ISSUE TITLE
Data Core issue. Eligibility/Quals/C-Shop/TiB CT-38474

### ISSUE THREAD

**Issue by skelebon** [501stLegionA3/FiveOhFirstDataCore#174] opened 2021-08-19 06:09 UTC
# Describe the bug
The Datacore does not correctly display my qualifications, C-Shop, or Time in Billet. Additionally, it does not automatically show that I am eligible for a promotion from Trooper to Senior Trooper.

# Expected behavior
My TiS is 124 days (maybe 125 now), which means I'm eligible. I also expect it to show my qualifications and that I'm a part of the Marksman C-Shop.

# Platform
Safari and Edge. Presumably all of browsers as I don't believe I showed up there either.

CT-38474 "Luck"

**Comment by Soyvolon** [comment] 2021-08-19 11:19
Talk to a roster clerk for data changes (cshops, quals, etc.)

Duplicate of #173

**Closed by Soyvolon** 2021-08-19 11:19 UTC
